# azure-pipelines-complete.yml
name: 'Docs-$(Date:yyyyMMdd)-$(Rev:r)'

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - 'specs/**'
      - 'docs-gen/**'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: pythonVersion
    value: '3.10'

stages:
  - stage: ValidateAndGenerate
    displayName: 'Validate and Generate Docs'
    jobs:
      - job: GenerateDocs
        displayName: 'Generate Documentation'
        steps:
          # 1. Checkout repository
          - checkout: self
            displayName: 'Checkout Repository'
            fetchDepth: 1
          
          # 2. Setup Python
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Setup Python $(pythonVersion)'
          
          # 4. Install dependencies
          - script: |
              python -m pip install --upgrade pip
              pip install -r 0DEV/api-spec-gen-func/requirements.txt
            displayName: 'Install Dependencies'
          
          # 5. Validate files exist
          - script: |
              if [ ! -f "0DEV/specs/eam-api.yaml" ]; then
                echo "❌ Error: 0DEV/specs/eam-api.yaml not found"
                exit 1
              fi
              if [ ! -f "0DEV/docs-gen/generate_docs.py" ]; then
                echo "❌ Error: 0DEV/docs-gen/generate_docs.py not found"
                exit 1
              fi
              echo "✅ All required files found"
            displayName: 'Validate Required Files'
          
          # 3. Cache pip packages (optional - speeds up builds)
          - task: Cache@2
            inputs:
              key: 'python | "$(Agent.OS)" | 0DEV/api-spec-gen-func/requirements.txt'
              restoreKeys: |
                python | "$(Agent.OS)"
              path: $(Pipeline.Workspace)/.pip
            displayName: 'Cache pip packages'
          - task: Cache@2
            inputs:
              key: 'python | "$(Agent.OS)" | 0DEV/api-spec-gen-func/requirements.txt'
              restoreKeys: |
                python | "$(Agent.OS)"
              path: $(HOME)/.cache/pip
            displayName: 'Cache pip packages'
            
          # 6. Generate documentation
          - script: |
              mkdir -p $(Build.ArtifactStagingDirectory)/docs
              
              python 0DEV/docs-gen/generate_docs.py \
                --spec 0DEV/specs/eam-api.yaml \
                --output-md $(Build.ArtifactStagingDirectory)/docs/api-documentation.md \
                --output-html $(Build.ArtifactStagingDirectory)/docs/api-documentation.html
              
              # Check if files were created
              if [ -f "$(Build.ArtifactStagingDirectory)/docs/api-documentation.md" ]; then
                echo "✅ Markdown documentation generated"
              fi
              if [ -f "$(Build.ArtifactStagingDirectory)/docs/api-documentation.html" ]; then
                echo "✅ HTML documentation generated"
              fi
            displayName: 'Generate Documentation'
            env:
              AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)
              AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)
              AZURE_OPENAI_DEPLOYMENT: $(AZURE_OPENAI_DEPLOYMENT)
          
          # 7. Publish artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/docs'
              ArtifactName: 'api-documentation-$(Build.BuildNumber)'
              publishLocation: 'Container'
            displayName: 'Publish Documentation Artifacts'

