# docs-gen/abbreviations.py
# Comprehensive abbreviations dictionary for API documentation

ABBREVIATIONS = {
    # IT Security
    "BGW": "Border Gateway",
    "MC": "Management Console",
    "IC": "Information Classification",
    "CIA": "Confidentiality, Integrity, Availability",
    "GDPR": "General Data Protection Regulation",
    "PII": "Personally Identifiable Information",
    "PHI": "Protected Health Information",
    "RBAC": "Role-Based Access Control",
    "ABAC": "Attribute-Based Access Control",
    "MFA": "Multi-Factor Authentication",
    "2FA": "Two-Factor Authentication",
    "SSO": "Single Sign-On",
    "SAML": "Security Assertion Markup Language",
    "OIDC": "OpenID Connect",
    "LDAP": "Lightweight Directory Access Protocol",
    "AD": "Active Directory",
    "IAM": "Identity and Access Management",
    "PAM": "Privileged Access Management",
    "SIEM": "Security Information and Event Management",
    "SOAR": "Security Orchestration, Automation and Response",
    "SOC": "Security Operations Center",
    "CSIRT": "Computer Security Incident Response Team",
    "ISMS": "Information Security Management System",
    "DLP": "Data Loss Prevention",
    "IDS": "Intrusion Detection System",
    "IPS": "Intrusion Prevention System",
    "WAF": "Web Application Firewall",
    "NGFW": "Next-Generation Firewall",
    "EDR": "Endpoint Detection and Response",
    "XDR": "Extended Detection and Response",
    "CASB": "Cloud Access Security Broker",
    "SASE": "Secure Access Service Edge",
    "ZTA": "Zero Trust Architecture",
    "VPN": "Virtual Private Network",
    "TLS": "Transport Layer Security",
    "SSL": "Secure Sockets Layer",
    "PKI": "Public Key Infrastructure",
    "CA": "Certificate Authority",
    "HSM": "Hardware Security Module",
    "KMS": "Key Management Service",
    "AES": "Advanced Encryption Standard",
    "RSA": "Rivest-Shamir-Adleman",
    "SHA": "Secure Hash Algorithm",
    "HMAC": "Hash-based Message Authentication Code",
    
    # Compliance & Standards
    "ISO": "International Organization for Standardization",
    "IEC": "International Electrotechnical Commission",
    "NIST": "National Institute of Standards and Technology",
    "OWASP": "Open Web Application Security Project",
    "PCI-DSS": "Payment Card Industry Data Security Standard",
    "HIPAA": "Health Insurance Portability and Accountability Act",
    "SOX": "Sarbanes-Oxley Act",
    "FISMA": "Federal Information Security Management Act",
    "FedRAMP": "Federal Risk and Authorization Management Program",
    "CCPA": "California Consumer Privacy Act",
    "CPRA": "California Privacy Rights Act",
    "PIPEDA": "Personal Information Protection and Electronic Documents Act",
    "LGPD": "Lei Geral de Proteção de Dados (Brazilian Data Protection Law)",
    "APPI": "Act on the Protection of Personal Information (Japan)",
    "CIS": "Center for Internet Security",
    "CSF": "Cybersecurity Framework",
    "COBIT": "Control Objectives for Information Technologies",
    "ITIL": "Information Technology Infrastructure Library",
    "TOGAF": "The Open Group Architecture Framework",
    
    # API & Technical
    "API": "Application Programming Interface",
    "REST": "Representational State Transfer",
    "SOAP": "Simple Object Access Protocol",
    "GraphQL": "Graph Query Language",
    "gRPC": "Google Remote Procedure Call",
    "JSON": "JavaScript Object Notation",
    "XML": "Extensible Markup Language",
    "YAML": "YAML Ain't Markup Language",
    "HTTP": "Hypertext Transfer Protocol",
    "HTTPS": "Hypertext Transfer Protocol Secure",
    "WebSocket": "Web Socket Protocol",
    "URL": "Uniform Resource Locator",
    "URI": "Uniform Resource Identifier",
    "URN": "Uniform Resource Name",
    "UUID": "Universally Unique Identifier",
    "GUID": "Globally Unique Identifier",
    "CRUD": "Create, Read, Update, Delete",
    "SDK": "Software Development Kit",
    "CLI": "Command Line Interface",
    "GUI": "Graphical User Interface",
    "IDE": "Integrated Development Environment",
    "CI/CD": "Continuous Integration/Continuous Deployment",
    "DevOps": "Development Operations",
    "DevSecOps": "Development Security Operations",
    "SRE": "Site Reliability Engineering",
    "SLA": "Service Level Agreement",
    "SLO": "Service Level Objective",
    "SLI": "Service Level Indicator",
    "KPI": "Key Performance Indicator",
    "RPO": "Recovery Point Objective",
    "RTO": "Recovery Time Objective",
    "MTBF": "Mean Time Between Failures",
    "MTTR": "Mean Time To Recovery",
    
    # Security Vulnerabilities
    "XSS": "Cross-Site Scripting",
    "CSRF": "Cross-Site Request Forgery",
    "SSRF": "Server-Side Request Forgery",
    "SQLi": "SQL Injection",
    "NoSQLi": "NoSQL Injection",
    "XXE": "XML External Entity",
    "RCE": "Remote Code Execution",
    "LFI": "Local File Inclusion",
    "RFI": "Remote File Inclusion",
    "IDOR": "Insecure Direct Object Reference",
    "DoS": "Denial of Service",
    "DDoS": "Distributed Denial of Service",
    "MITM": "Man-In-The-Middle",
    "CVE": "Common Vulnerabilities and Exposures",
    "CWE": "Common Weakness Enumeration",
    "CVSS": "Common Vulnerability Scoring System"
}